server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: titlecounter
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
token:
  signing:
    key: ${TOKEN_SIGNING}