server:
  port: 80
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: title-counter-api
          uri: lb:http://title-counter-api
          predicates:
            - Path=/api/**
        - id: notifications-api
          uri: lb:http://notification-service
          predicates:
            - Path=/notification/**
#        - id: title-counter-front
#          uri: lb:http://title-counter-front
#          predicates:
#            - Path=/**
      default-filters:
        - RemoveRequestHeader=authorities
        - RemoveRequestHeader=username
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  accessExpirationTimeout: 15 # minutes
  refreshExpirationTimeout: 24 # hours
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      -   name: title-counter-api
          url: lb:http://title-counter-api/v3/api-docs

