services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=TitleCounter'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - 5432
    ports:
      - '15432:5432'
    networks:
      net:
  eureka-server:
    build: 'server/eureka-server'
    container_name: 'eureka-server'
    restart: 'always'
    ports:
      - '8761:8761'
    networks:
      net:
  gateway-service:
    build: 'server/gateway-service'
    container_name: 'gateway-service'
    restart: "always"
    ports:
      - '80:80'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TOKEN_SIGNING: ${TOKEN_SIGNING}
    networks:
      net:
  title-counter-api:
    build: 'server/backend-app'
    volumes:
      - './resources:/resources'
    container_name: 'title-counter-api'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/TitleCounter
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TOKEN_SIGNING: ${TOKEN_SIGNING}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      net:
  external-api:
    build: 'external-api-service'
    container_name: 'external-api-service'
    networks:
      net:
networks:
  net:
    driver: bridge
