 INSERT INTO game_genres VALUES
     (1, 'Simulation'),
     (2, 'Third-Person'),
     (3, 'Action'),
     (4, 'Platform'),
     (5, 'Puzzle'),
     (6, 'Racing/Driving'),
     (7, 'Beat em Up'),
     (8, 'Adventure'),
     (9, 'Scrolling'),
     (10, 'Role-Playing'),
     (11, 'Music/Rhythm'),
     (12, 'Strategy'),
     (13, 'First-Person'),
     (14, 'Shooter'),
     (15, 'Card Game'),
     (16, 'Sports'),
     (17, 'Top-Down'),
     (18, 'Survival Horror'),
     (19, 'Stealth'),
     (20, 'Arcade'),
     (21, 'Hack and Slash'),
     (22, 'Visual Novel'),
     (23, 'Turn-Based'),
     (24, 'Massively Multiplayer'),
     (25, 'Compilation'),
     (26, 'Fighting'),
     (27, 'Tactical'),
     (28, 'Hidden Object'),
     (29, 'Board Game'),
     (30, 'Battle Arena'),
     (31, 'Real-Time'),
     (32, 'Party'),
     (33, 'Isometric'),
     (34, 'City-Building'),
     (35, 'Strategy/Tactical'),
     (36, 'Text'),
     (37, 'Interactive Art'),
     (38, 'Open World'),
     (39, 'Educational'),
     (40, 'Roguelike'),
     (41, 'Flight'),
     (42, 'Car Combat'),
     (43, 'Point-and-Click'),
     (44, 'Flight Combat'),
     (45, 'Side'),
     (46, 'Sandbox'),
     (47, 'On-Rails'),
     (48, 'Multidirectional'),
     (49, 'Social'),
     (50, 'Tower Defense'),
     (51, 'Pinball'),
     (52, 'Breakout'),
     (53, 'Horror'),
     (54, 'Survival'),
     (55, 'Virtual Reality'),
     (56, 'Trivia'),
     (57, 'Moba'),
     (58, 'Management'),
     (59, 'Vehicular Combat');

SELECT pg_catalog.setval('game_genres_id_seq', 59, true);