CREATE TABLE IF NOT EXISTS game_genres (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE game_genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE game_genres DROP CONSTRAINT IF EXISTS game_genres_pkey CASCADE;
ALTER TABLE ONLY game_genres ADD CONSTRAINT game_genres_pkey PRIMARY KEY (id);

ALTER TABLE ONLY game_genres DROP CONSTRAINT IF EXISTS unique_game_genre_name_idx;
ALTER TABLE ONLY game_genres ADD CONSTRAINT unique_game_genre_name_idx UNIQUE (name);