CREATE TABLE IF NOT EXISTS game_developers (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL DEFAULT 'unknown'
);

ALTER TABLE game_developers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_developers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE game_developers DROP CONSTRAINT IF EXISTS game_developers_pkey CASCADE;
ALTER TABLE ONLY game_developers ADD CONSTRAINT game_developers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY game_developers DROP CONSTRAINT IF EXISTS unique_game_developer_name_idx;
ALTER TABLE ONLY game_developers ADD CONSTRAINT unique_game_developer_name_idx UNIQUE (name);


CREATE TABLE IF NOT EXISTS games_game_developers (
    game_id bigint NOT NULL,
    game_developer_id bigint NOT NULL
);

ALTER TABLE games_game_developers DROP CONSTRAINT IF EXISTS games_game_developers_game_id_fk;
ALTER TABLE ONLY games_game_developers
    ADD CONSTRAINT games_game_developers_game_id_fk FOREIGN KEY (game_id) REFERENCES games(id);
ALTER TABLE games_game_developers DROP CONSTRAINT IF EXISTS games_game_developers_genre_id_fk;
ALTER TABLE ONLY games_game_developers
    ADD CONSTRAINT games_game_developers_genre_id_fk FOREIGN KEY (game_developer_id) REFERENCES game_developers(id);