CREATE TABLE IF NOT EXISTS game_platforms (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    alias character varying(255)
);

ALTER TABLE game_platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME game_platforms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE game_platforms DROP CONSTRAINT IF EXISTS game_platforms_pkey CASCADE;
ALTER TABLE ONLY game_platforms ADD CONSTRAINT game_platforms_pkey PRIMARY KEY (id);

ALTER TABLE ONLY game_platforms DROP CONSTRAINT IF EXISTS unique_game_platform_name_idx;
ALTER TABLE ONLY game_platforms ADD CONSTRAINT unique_game_platform_name_idx UNIQUE (name);


CREATE TABLE IF NOT EXISTS games_game_platforms (
    game_id bigint NOT NULL,
    game_platform_id bigint NOT NULL
);

ALTER TABLE games_game_platforms DROP CONSTRAINT IF EXISTS games_game_platforms_game_id_fk;
ALTER TABLE ONLY games_game_platforms
    ADD CONSTRAINT games_game_platforms_game_id_fk FOREIGN KEY (game_id) REFERENCES games(id);
ALTER TABLE games_game_platforms DROP CONSTRAINT IF EXISTS games_game_platforms_platforms_id_fk;
ALTER TABLE ONLY games_game_platforms
    ADD CONSTRAINT games_game_platforms_platforms_id_fk FOREIGN KEY (game_platform_id) REFERENCES game_platforms(id);