services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=TitleCounter'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    expose:
      - 5432
    ports:
      - '15432:5432'
    networks:
      net:
  eureka-server:
    build: 'eureka-server/'
    container_name: 'eureka-server'
    restart: 'always'
    ports:
      - '8761:8761'
    networks:
      net:
  gateway-service:
    build: 'gateway-service/'
    container_name: 'gateway-service'
    restart: "always"
    ports:
      - '80:80'
    environment:
      - spring.profiles.active=prod
    networks:
      net:
  title-counter-api:
    build: 'backend-app/'
    container_name: 'title-counter-api'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/TitleCounter
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      net:
networks:
  net:
    driver: bridge
