spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/TitleCounter
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
app:
  publicUrl: ${PUBLIC_URL}
  scheduler:
    enabled: true
    interval: PT12H
  rabbitmq:
    enabled: false
token:
  signing:
    key: ${TOKEN_SIGNING}