spring:
  application:
    name: title-counter-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TitleCounter
    username: postgres
    password: 1234
  jpa:
    show-sql: false
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false
  thymeleaf:
    cache: false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
server:
  port: 8080
  servlet:
    session:
      timeout: 15m
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  accessExpirationTimeout: 15 # minutes
  refreshExpirationTimeout: 24 # hours
app:
  scheduler:
    enabled: true
    interval: PT12H
  publicUrl: localhost
  rabbitmq:
    queue:
      name: greetings.notifications
    exchange:
      name: title-counter.direct
    routing:
      key: register.complete
springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /myproject
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      -   name: title-counter-api
#          url: lb://title-counter-api/v3/api-docs

#http://localhost:9000/oauth2/authorize?response_type=code&client_id=title_counter_client&redirect_uri=http://127.0.0.1:9090/login/oauth2/code/title_counter_client&scope=addTitles+deleteTitles