spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TitleCounter
    username: postgres
    password: 1234
  flyway:
    user: postgres
    password: 1234
    schemas: dev
    baselineOnMigrate: true
    enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: dev
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: localhost
    username: guest
    password: guest
app:
  publicUrl: http://localhost:8080
  scheduler:
    enabled: false
    interval: PT12H