spring:
  application:
    name: title-counter-api
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/TitleCounter
    username: postgres
    password: 1234
  flyway:
    user: postgres
    password: 1234
    schemas: dev
    url: jdbc:postgresql://localhost:5432/TitleCounter
    baselineOnMigrate: true
    enabled: false
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: dev
  jba:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  #  redis:
  #    host: localhost
  #    port: 6379
  #  session:
  #    redis:
  #      flush-mode: on_save
  #      namespace: title_counter:session
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  thymeleaf:
    cache: false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
server:
  port: 8080
  servlet:
    session:
      timeout: 15m
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  accessExpirationTimeout: 15 # minutes
  refreshExpirationTimeout: 24 # hours
app:
  rabbitmq:
    queue:
      name: greetings.notifications
    exchange:
      name: title-counter.direct
    routing:
      key: register.complete
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

#http://localhost:9000/oauth2/authorize?response_type=code&client_id=title_counter_client&redirect_uri=http://127.0.0.1:9090/login/oauth2/code/title_counter_client&scope=addTitles+deleteTitles