spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TitleCounter
    username: postgres
    password: 1234
  flyway:
    user: postgres
    password: 1234
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/