server:
  port: 8081
spring:
  application:
    name: notification-service
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: dev
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_GOOGLE_USERNAME}
    password: ${MAIL_GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
app:
  notification:
    email:
      enabled: true
    logger:
      enabled: false
  rabbitmq:
    queue:
      name: greetings.notifications