name: Build Backend app

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/backend-app/**'
      - '.github/workflows/backend-app.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'server/backend-app/**'
      - '.github/workflows/backend-app.yml'


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build
    environment: Test
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    permissions:
      packages: write
      pull-requests: write

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: maven build
        working-directory: ./server
        run: mvn -pl backend-app -am package

      - name: Get directory target
        working-directory: ./server/backend-app/target
        run: ls

      - name: Get directory ba
        working-directory: ./server/backend-app
        run: ls

      - name: Get directory server
        working-directory: ./server/
        run: ls

      - name: Run tests
        working-directory: ./server
        run: mvn -pl backend-app -am verify

      - name: Login to docker.io
        #working-directory: ./server
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master

      - name: Build backend-app image
        #working-directory: ./server/backend-app
        run: docker build -t $LOGIN/$NAME:backend-app.latest server/backend-app

      - name: Push image to docker.io
        #working-directory: ./server/backend-app
        run: docker push $LOGIN/$NAME:backend-app.latest