name: Build Backend app

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/backend-app/**'
      - '.github/workflows/backend-app.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'server/backend-app/**'
      - '.github/workflows/backend-app.yml'


env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  NAME: ${{ secrets.DOCKER_NAME }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build
    environment: Test
    permissions:
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: change directory
        run: cd server

      - name: maven build
        run: mvn -pl backend-app -am package

      - name: Run tests
        run: mvn -pl backend-app -am verify

      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t $LOGIN/$NAME:backend-app.${GITHUB_REF:11} backend-app

      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:backend-app.${GITHUB_REF:11}